
#ifndef __UTF8_READERSTATUS__H_
#define __UTF8_READERSTATUS__H_

typedef enum ucReaderStatus {
    UCREADERSTATUS_CONTINUE = -1,
    UCREADERSTATUS_OK = 0,

    UCREADERSTATUS_ERROR = 1,
    UCREADERSTATUS_ERROR_UNEXPECTED_EOF,

    UCREADERSTATUS_ERROR_INVALID_UTF8_STARTBYTE_SEQUENCEBYTE,
    UCREADERSTATUS_ERROR_INVALID_UTF8_STARTBYTE_OVERLONG_ENCODING,
    UCREADERSTATUS_ERROR_INVALID_UTF8_STARTBYTE_OUT_OF_RANGE,

    UCREADERSTATUS_ERROR_INVALID_UTF8_SEQUENCEBYTE,

} ucReaderStatus;

#endif
